apiVersion: v1
kind: PersistentVolume
metadata:
  name: sns-ebs-pv
  namespace: prod
spec:
  volumeMode: Filesystem
  capacity:
    storage: 5Gi # 볼륨의 크기
  accessModes:
    - ReadWriteOnce # 하나 Pod에 마운트
  awsElasticBlockStore:
    volumeID: vol-0e641d93bd79fd3cb
  persistentVolumeReclaimPolicy: Retain