server:
  port: 8088
spring:
  config:
    activate:
      on-profile: local,dev,prod
  application:
    name: sns-service
  # config service settings
  cloud:
    config:
      name: sns-service
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
  jackson:
    time-zone: Asia/Seoul
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, busrefresh, circuitbreakers
  health:
    circuitbreakers:
      enabled: true
feign:
  circuitbreaker:
    enabled: true
